import { useState, useEffect, useCallback, useRef } from 'react';
import { Upload, FileCode2, Hash, Code, BookTemplate, Layers, Download, Search } from 'lucide-react';

const categorizeImport = (imp) => {
  const lower = imp.toLowerCase();
  if (lower.includes('internet') || lower.includes('socket') || lower.includes('wininet') || lower.includes('ws2') || lower.includes('bind')) return { cat: 'Networking', color: 'text-blue-400', bg: 'bg-blue-500/20', border: 'border-blue-500/30' };
  if (lower.includes('crypt') || lower.includes('bcrypt') || lower.includes('ssl') || lower.includes('tls')) return { cat: 'Cryptography', color: 'text-yellow-400', bg: 'bg-yellow-500/20', border: 'border-yellow-500/30' };
  if (lower.includes('virtualalloc') || lower.includes('writeprocess') || lower.includes('createremotethread') || lower.includes('ptrace')) return { cat: 'Process Injection', color: 'text-red-400', bg: 'bg-red-500/20', border: 'border-red-500/30' };
  if (lower.includes('createfile') || lower.includes('writefile') || lower.includes('deletefile') || lower.includes('fopen')) return { cat: 'File I/O', color: 'text-emerald-400', bg: 'bg-emerald-500/20', border: 'border-emerald-500/30' };
  return { cat: 'Standard', color: 'text-slate-400', bg: 'bg-slate-700/50', border: 'border-slate-600' };
};

export default function Scanner({ result, setResult, expectedHash, setExpectedHash, isWasmLoaded, error, setError }) {
  const [isDragging, setIsDragging] = useState(false);
  const [stringSearch, setStringSearch] = useState('');
  const fileInputRef = useRef(null);

  const handleExportHTML = () => {
    if (!result) return;

    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RevBench Analysis Report - ${result.info.format}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { background-color: #0b101e; color: #cbd5e1; font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; }
        .card { background-color: #111928; border: 1px solid #1f2937; border-top: 2px solid #00d4ff; }
        .header-gradient { background: linear-gradient(to right, #00d4ff, #0088ff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        ::-webkit-scrollbar { width: 8px; }
        ::-webkit-scrollbar-track { background: #0b101e; }
        ::-webkit-scrollbar-thumb { background: #1f2937; border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: #374151; }
    </style>
</head>
<body class="p-8">
    <div class="max-w-6xl mx-auto">
        <header class="mb-12 border-b border-slate-800 pb-8 flex justify-between items-end">
            <div>
                <h1 class="text-4xl font-extrabold mb-2 header-gradient">RevBench Analysis Report</h1>
                <p class="text-slate-400">Static Binary Analysis Results • ${result.info.time}</p>
            </div>
            <div class="text-right">
                <div class="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Generated By</div>
                <div class="text-sm font-bold text-white">RevBench v1.0</div>
            </div>
        </header>

        <div class="grid md:grid-cols-3 gap-6 mb-8">
            <!-- File Info -->
            <div class="card p-6 rounded-sm shadow-xl">
                <h3 class="text-lg font-bold text-white mb-6 border-b border-slate-700/50 pb-3 flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#00d4ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><line x1="10" y1="9" x2="8" y2="9"/></svg>
                    File Info
                </h3>
                <div class="space-y-3">
                    <div class="flex justify-between items-center bg-slate-900/50 p-2 rounded border border-slate-800">
                        <span class="text-slate-500 text-xs font-bold uppercase tracking-tighter">Format</span>
                        <span class="text-white font-mono text-xs">${result.info.format}</span>
                    </div>
                    <div class="flex justify-between items-center bg-slate-900/50 p-2 rounded border border-slate-800">
                        <span class="text-slate-500 text-xs font-bold uppercase tracking-tighter">Arch</span>
                        <span class="text-white font-mono text-xs">${result.info.arch}</span>
                    </div>
                    <div class="flex justify-between items-center bg-slate-900/50 p-2 rounded border border-slate-800">
                        <span class="text-slate-500 text-xs font-bold uppercase tracking-tighter">Size</span>
                        <span class="text-white font-mono text-xs">${(result.info.size / 1024).toFixed(2)} KB</span>
                    </div>
                    <div class="flex justify-between items-center bg-slate-900/50 p-2 rounded border border-slate-800">
                        <span class="text-slate-500 text-xs font-bold uppercase tracking-tighter">Language</span>
                        <span class="text-white font-mono text-xs">${result.info.language}</span>
                    </div>
                </div>
            </div>

            <!-- Traits -->
            <div class="card p-6 rounded-sm shadow-xl">
                <h3 class="text-lg font-bold text-white mb-6 border-b border-slate-700/50 pb-3 flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#00d4ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>
                    Traits
                </h3>
                <div class="space-y-4">
                    <div class="bg-slate-900/50 p-3 rounded border border-slate-800">
                        <div class="text-slate-300 font-bold text-sm mb-1">${result.info.linking}</div>
                        <p class="text-slate-500 text-[11px] leading-relaxed">${result.info.linking === "Statically Linked" ? "The binary includes all dependencies within itself." : "The binary relies on external shared libraries."}</p>
                    </div>
                    <div class="bg-slate-900/50 p-3 rounded border border-slate-800">
                        <div class="text-slate-300 font-bold text-sm mb-1">${result.info.stripped}</div>
                        <p class="text-slate-500 text-[11px] leading-relaxed">${result.info.stripped === "Stripped" ? "The symbol table has been removed, making analysis harder." : "The symbol table is present, facilitating reverse engineering."}</p>
                    </div>
                </div>
            </div>

            <!-- Hashes -->
            <div class="card p-6 rounded-sm shadow-xl">
                <h3 class="text-lg font-bold text-white mb-6 border-b border-slate-700/50 pb-3 flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#00d4ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="9" x2="20" y2="9"/><line x1="4" y1="15" x2="20" y2="15"/><line x1="10" y1="3" x2="8" y2="21"/><line x1="16" y1="3" x2="14" y2="21"/></svg>
                    Hashes
                </h3>
                <div class="space-y-3">
                    ${Object.entries(result.hashes).map(([alg, hash]) => `
                        <div class="bg-slate-900/50 p-3 rounded border border-slate-800">
                            <div class="text-slate-500 font-bold uppercase text-[10px] tracking-widest mb-1">${alg}</div>
                            <div class="text-emerald-400 font-mono text-[10px] break-all leading-tight">${hash}</div>
                        </div>
                    `).join('')}
                </div>
            </div>
        </div>

        <!-- Imports -->
        <div class="card p-6 rounded-sm mb-8 shadow-xl">
            <h3 class="text-lg font-bold text-white mb-4 border-b border-slate-700/50 pb-3 flex items-center justify-between">
                <span class="flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#00d4ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>
                    Import Address Table
                </span>
                <span class="text-xs bg-blue-500/20 text-blue-400 px-2 py-1 rounded border border-blue-500/30">${result.imports?.length || 0} Entries</span>
            </h3>
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-2">
                ${result.imports?.map(imp => `
                    <div class="p-2 bg-slate-900/30 border border-slate-800/50 rounded font-mono text-[10px] text-slate-300 truncate hover:bg-slate-800/50 transition-colors" title="${imp}">${imp}</div>
                `).join('') || '<div class="col-span-4 text-slate-500 italic text-center py-4">No imports detected</div>'}
            </div>
        </div>

        <!-- Data Section -->
        ${result.data_section ? `
        <div class="card p-6 rounded-sm shadow-xl mb-8">
            <h3 class="text-lg font-bold text-white mb-4 border-b border-slate-700/50 pb-3 flex items-center justify-between">
                <span class="flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#00d4ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>
                    .data Section (objdump -s -j .data)
                </span>
            </h3>
            <div class="max-h-[500px] overflow-y-auto bg-slate-900/30 p-4 rounded border border-slate-800 custom-scrollbar">
                <pre class="font-mono text-[11px] text-slate-400 whitespace-pre-wrap">${result.data_section.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
            </div>
        </div>
        ` : ''}

        <!-- Strings -->
        <div class="card p-6 rounded-sm shadow-xl">
            <h3 class="text-lg font-bold text-white mb-4 border-b border-slate-700/50 pb-3 flex items-center justify-between">
                <span class="flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#00d4ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>
                    Extracted Strings
                </span>
                <span class="text-xs bg-purple-500/20 text-purple-400 px-2 py-1 rounded border border-purple-500/30">${result.strings?.length || 0} Found</span>
            </h3>
            <div class="max-h-[500px] overflow-y-auto bg-slate-900/30 p-4 rounded border border-slate-800 custom-scrollbar">
                <div class="space-y-1">
                    ${result.strings?.map(str => `
                        <div class="font-mono text-[11px] text-slate-400 break-all border-b border-slate-800/50 pb-1.5 mb-1.5 last:border-0 last:mb-0 hover:text-white transition-colors">${str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
                    `).join('') || '<div class="text-slate-500 italic text-center py-4">No strings found</div>'}
                </div>
            </div>
        </div>

        <footer class="mt-12 pt-8 border-t border-slate-800 text-center text-slate-600 text-xs tracking-widest uppercase">
            &copy; ${new Date().getFullYear()} RevBench Analysis System • Secure Local Browser Parsing
        </footer>
    </div>
</body>
</html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const filename = `RevBench_Report_${result.info.format}_${result.hashes.sha256.substring(0, 8)}.html`;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };





  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const processFile = async (file) => {
    setError(null);
    setResult(null);
    setExpectedHash('');

    if (!isWasmLoaded) {
      setError("WebAssembly engine is not ready yet.");
      return;
    }

    try {
      const buffer = await file.arrayBuffer();
      const uint8Array = new Uint8Array(buffer);
      
      const jsonResult = window.RevBench_parseBinary(uint8Array);
      const parsed = JSON.parse(jsonResult);
      
      if (parsed.error) {
        setError(parsed.error);
      } else {
        setResult(parsed);
      }
    } catch (err) {
      setError("Error processing file: " + err.message);
    }
  };

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    setIsDragging(false);

    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      processFile(e.dataTransfer.files[0]);
    }
  }, [isWasmLoaded]);

  const handleFileSelect = (e) => {
    if (e.target.files && e.target.files.length > 0) {
      processFile(e.target.files[0]);
    }
  };

  return (
    <div className="flex flex-col h-full max-w-full px-6 mx-auto">
      <div className="mb-8 flex justify-between items-end">
        <div>
          <h2 className="text-3xl font-bold mb-2 text-white">Static Binary Analyzer</h2>
          <p className="text-slate-400">Securely parse binary files in your browser using Go WebAssembly. No files are uploaded to any server.</p>
        </div>
        {result && (
          <button 
            onClick={handleExportHTML}
            className="flex items-center gap-2 bg-[#00d4ff] hover:bg-[#00d4ff]/80 text-[#0b101e] px-6 py-2.5 rounded-sm transition-all font-bold uppercase tracking-wider text-sm shadow-lg shadow-[#00d4ff]/20 active:scale-95"
          >
            <Download size={18} />
            Export HTML
          </button>
        )}
      </div>
      
      {/* Drag & Drop Zone */}
      <input 
        type="file" 
        ref={fileInputRef} 
        onChange={handleFileSelect} 
        className="hidden" 
      />
      <div 
        onClick={() => fileInputRef.current?.click()}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
        className={`border-2 border-dashed rounded-sm p-12 text-center transition-all duration-200 cursor-pointer flex flex-col items-center justify-center min-h-[250px] mb-8
          ${isDragging ? 'border-[#00d4ff] bg-[#00d4ff]/10' : 'border-[#1f2937] bg-[#111928] hover:border-[#374151]'}`}
      >
        <div className={`p-4 mb-4 transition-colors ${isDragging ? 'text-[#00d4ff]' : 'text-gray-500'}`}>
          <Upload size={48} />
        </div>
        <h3 className="text-2xl font-bold text-white mb-2">
          {isDragging ? 'Drop binary here' : 'Click or drag & drop a binary file'}
        </h3>
        <p className="text-slate-400">
          Supports ELF and PE files
        </p>
        {!isWasmLoaded && !error && (
          <div className="mt-6 inline-flex items-center gap-2 text-yellow-500 bg-yellow-500/10 px-4 py-2 rounded-full text-sm font-medium border border-yellow-500/20">
            <span className="w-2 h-2 rounded-full bg-yellow-500 animate-ping"></span>
            Loading Wasm Engine...
          </div>
        )}
      </div>

      {/* Error Message */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/50 text-red-400 p-4 rounded-xl mb-8 flex items-center gap-3">
          <div className="w-1.5 h-8 bg-red-500 rounded-full"></div>
          <p className="font-medium">{error}</p>
        </div>
      )}

      {/* Results Dashboard */}
      {result && (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12">
          
          {/* File Info */}
          <div className="bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm lg:col-span-1">
            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-700/80">
              <div className="p-2 bg-blue-500/20 rounded-lg">
                <FileCode2 className="text-blue-400" size={20} />
              </div>
              <h3 className="text-xl font-bold text-white">File Information</h3>
            </div>
            <div className="space-y-4">
              <div className="flex justify-between items-center bg-slate-900/50 p-3 rounded-lg border border-slate-800/80">
                <span className="text-slate-400 font-medium text-sm uppercase tracking-wider">Format</span>
                <span className="text-white font-mono bg-slate-800 px-3 py-1 rounded-md border border-slate-700">{result.info.format}</span>
              </div>
              <div className="flex justify-between items-center bg-slate-900/50 p-3 rounded-lg border border-slate-800/80">
                <span className="text-slate-400 font-medium text-sm uppercase tracking-wider">Architecture</span>
                <span className="text-white font-mono bg-slate-800 px-3 py-1 rounded-md border border-slate-700">{result.info.arch}</span>
              </div>
              <div className="flex justify-between items-center bg-slate-900/50 p-3 rounded-lg border border-slate-800/80">
                <span className="text-slate-400 font-medium text-sm uppercase tracking-wider">Size</span>
                <span className="text-white font-mono bg-slate-800 px-3 py-1 rounded-md border border-slate-700">{(result.info.size / 1024).toFixed(2)} KB</span>
              </div>
              <div className="flex justify-between items-center bg-slate-900/50 p-3 rounded-lg border border-slate-800/80">
                <span className="text-slate-400 font-medium text-sm uppercase tracking-wider">Language</span>
                <span className="text-white font-mono bg-slate-800 px-3 py-1 rounded-md border border-slate-700">{result.info.language}</span>
              </div>
              <div className="flex justify-between items-center bg-slate-900/50 p-3 rounded-lg border border-slate-800/80">
                <span className="text-slate-400 font-medium text-sm uppercase tracking-wider">Time</span>
                <span className="text-white font-mono bg-slate-800 px-3 py-1 rounded-md border border-slate-700">{result.info.time}</span>
              </div>
            </div>
          </div>

          {/* Compilation Traits */}
          <div className="bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm lg:col-span-1">
            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-700/80">
              <div className="p-2 bg-amber-500/20 rounded-lg">
                <FileCode2 className="text-amber-400" size={20} />
              </div>
              <h3 className="text-xl font-bold text-white">Compilation Traits</h3>
            </div>
            <div className="space-y-4">
              <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-800/80">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-slate-300 font-medium tracking-wider">{result.info.linking}</span>
                </div>
                <p className="text-slate-500 text-sm leading-relaxed">
                  {result.info.linking === "Statically Linked" 
                    ? "The binary includes all of its dependencies within itself. It is larger but doesn't require external libraries to run."
                    : result.info.linking === "Dynamically Linked" 
                      ? "The binary relies on external shared libraries on the host system to run. This makes it smaller but requires the system to provide dependencies."
                      : "Linking information could not be determined."}
                </p>
              </div>

              <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-800/80">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-slate-300 font-medium tracking-wider">{result.info.stripped}</span>
                </div>
                <p className="text-slate-500 text-sm leading-relaxed">
                  {result.info.stripped === "Stripped" 
                    ? "The symbol table has been removed. This makes reverse engineering significantly harder as function and variable names are missing."
                    : result.info.stripped === "Not Stripped" 
                      ? "The symbol table is present. This is a goldmine for reverse engineers, as original function names and variables are intact."
                      : "Stripping information could not be determined."}
                </p>
              </div>
            </div>
          </div>

          {/* Hashes */}
          <div className="bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm lg:col-span-1">
            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-700/80">
              <div className="p-2 bg-emerald-500/20 rounded-lg">
                <Hash className="text-emerald-400" size={20} />
              </div>
              <h3 className="text-xl font-bold text-white">Hashes</h3>
            </div>
            <div className="space-y-4">
              {Object.entries(result.hashes).map(([alg, hash]) => (
                <div key={alg} className="bg-slate-900/50 p-4 rounded-lg border border-slate-800/80">
                  <div className="text-slate-500 font-bold uppercase text-xs mb-2 tracking-widest">{alg}</div>
                  <div className="text-emerald-400 font-mono text-sm break-all select-all leading-relaxed">{hash}</div>
                </div>
              ))}
              
              <div className="mt-4 pt-4 border-t border-[#1f2937]">
                <label className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-2 block">Compare Hash (Optional)</label>
                <input 
                  type="text" 
                  value={expectedHash}
                  onChange={(e) => setExpectedHash(e.target.value)}
                  placeholder="Paste expected SHA256..."
                  className="w-full bg-[#0b101e] border border-[#1f2937] rounded-sm p-2 text-[#00d4ff] font-mono text-sm focus:outline-none focus:border-[#00d4ff] placeholder-gray-600"
                />
                {expectedHash && (
                  <div className={`mt-3 p-2 rounded-sm text-xs font-bold text-center ${expectedHash.trim().toLowerCase() === result.hashes.sha256.toLowerCase() ? 'bg-emerald-900/30 text-[#00d4ff] border border-[#00d4ff]' : 'bg-red-900/30 text-red-400 border border-red-500/50'}`}>
                    {expectedHash.trim().toLowerCase() === result.hashes.sha256.toLowerCase() ? '✓ HASH MATCH' : '✗ HASH MISMATCH'}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Imports Table */}
          <div className="md:col-span-2 lg:col-span-3 bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm flex flex-col h-[500px]">
            <div className="flex items-center justify-between mb-4 pb-4 border-b border-slate-700/80">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-orange-500/20 rounded-lg">
                  <BookTemplate className="text-orange-400" size={20} />
                </div>
                <h3 className="text-xl font-bold text-white">Import Address Table (IAT)</h3>
              </div>
              <div className="text-sm font-medium text-orange-300 bg-orange-500/20 px-3 py-1 rounded-full border border-orange-500/30">
                {result.imports?.length || 0} imports found
              </div>
            </div>
            
            <div className="flex-1 overflow-y-auto pr-2 rounded-lg border border-slate-800 bg-slate-900/30">
              {result.imports && result.imports.length > 0 ? (
                <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2 p-3">
                  {result.imports.map((imp, idx) => {
                    const catInfo = categorizeImport(imp);
                    return (
                      <li key={idx} className={`p-2 rounded border font-mono text-sm flex justify-between items-center transition-colors ${catInfo.bg} ${catInfo.border} hover:bg-slate-700`}>
                        <span className="text-slate-200 truncate mr-2" title={imp}>{imp}</span>
                        {catInfo.cat !== 'Standard' && (
                          <span className={`text-[10px] uppercase font-bold px-1.5 py-0.5 rounded ${catInfo.color} bg-black/30 whitespace-nowrap`}>
                            {catInfo.cat}
                          </span>
                        )}
                      </li>
                    );
                  })}
                </ul>
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-slate-500 italic">
                  <p>No imports detected.</p>
                  <p className="text-sm mt-2">Statically linked binaries or obfuscated files often hide their IAT.</p>
                </div>
              )}
            </div>
          </div>

          {/* Embedded Signatures (Binwalk) */}
          <div className="md:col-span-2 lg:col-span-3 bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm">
            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-700/80">
              <div className="p-2 bg-pink-500/20 rounded-lg">
                <Layers className="text-pink-400" size={20} />
              </div>
              <h3 className="text-xl font-bold text-white">Embedded Signatures (Binwalk-lite)</h3>
            </div>
            {result.embedded_files && result.embedded_files.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {result.embedded_files.map((file, idx) => (
                  <div key={idx} className="flex justify-between items-center bg-slate-900/50 p-3 rounded-lg border border-slate-800/80 hover:border-pink-500/50 transition-colors">
                    <span className="text-pink-400 font-semibold text-sm">{file.type}</span>
                    <span className="text-slate-400 font-mono text-xs bg-black/40 px-2 py-1 rounded">Offset: 0x{file.offset.toString(16).toUpperCase()}</span>
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-6 text-center text-slate-500 italic bg-slate-900/30 rounded-lg border border-slate-800/50">
                No embedded files or known signatures detected.
              </div>
            )}
          </div>

          {/* Internal Symbols */}
          <div className="md:col-span-2 lg:col-span-3 bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm flex flex-col h-[500px]">
            <div className="flex items-center justify-between mb-4 pb-4 border-b border-slate-700/80">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-yellow-500/20 rounded-lg">
                  <BookTemplate className="text-yellow-400" size={20} />
                </div>
                <h3 className="text-xl font-bold text-white">Internal Symbols (.symtab)</h3>
              </div>
              <div className="text-sm font-medium text-yellow-300 bg-yellow-500/20 px-3 py-1 rounded-full border border-yellow-500/30">
                {result.symbols?.length || 0} symbols found
              </div>
            </div>
            
            <div className="flex-1 overflow-y-auto pr-2 rounded-lg border border-slate-800 bg-slate-900/30">
              {result.symbols && result.symbols.length > 0 ? (
                <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2 p-3">
                  {result.symbols.map((sym, idx) => (
                    <li key={idx} className="p-2 rounded border border-slate-700/50 font-mono text-sm text-slate-300 bg-slate-800/30 hover:bg-slate-700 transition-colors truncate" title={sym}>
                      {sym}
                    </li>
                  ))}
                </ul>
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-slate-500 italic">
                  <p>No internal symbols detected.</p>
                  <p className="text-sm mt-2">This binary has been stripped of its internal symbol table.</p>
                </div>
              )}
            </div>
          </div>

          {/* Extracted Strings Table */}
          <div className="md:col-span-2 lg:col-span-3 bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm flex flex-col h-[600px]">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-4 pb-4 border-b border-slate-700/80 gap-4">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-purple-500/20 rounded-lg">
                  <Code className="text-purple-400" size={20} />
                </div>
                <h3 className="text-xl font-bold text-white">Extracted Strings</h3>
              </div>
              <div className="flex items-center gap-4">
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <Search className="h-4 w-4 text-slate-500" />
                  </div>
                  <input
                    type="text"
                    value={stringSearch}
                    onChange={(e) => setStringSearch(e.target.value)}
                    placeholder="Search strings..."
                    className="block w-full sm:w-64 pl-10 pr-3 py-2 border border-[#1f2937] rounded-sm leading-5 bg-[#0b101e] text-slate-300 placeholder-slate-500 focus:outline-none focus:border-[#00d4ff] transition duration-150 ease-in-out sm:text-sm"
                  />
                </div>
                <div className="text-sm font-medium text-purple-300 bg-purple-500/20 px-3 py-1 rounded-full border border-purple-500/30 whitespace-nowrap">
                  {result.strings.filter(s => s.toLowerCase().includes(stringSearch.toLowerCase())).length} strings found
                </div>
              </div>
            </div>
            
            <div className="flex-1 overflow-y-auto pr-2 rounded-lg border border-slate-800 bg-slate-900/30">
              {result.strings.length > 0 ? (
                <ul className="divide-y divide-slate-800/80">
                  {result.strings.filter(s => s.toLowerCase().includes(stringSearch.toLowerCase())).map((str, idx) => (
                    <li key={idx} className="p-3 font-mono text-base text-slate-300 hover:bg-slate-800/50 hover:text-white transition-colors break-all">
                      {str}
                    </li>
                  ))}
                </ul>
              ) : (
                <div className="h-full flex items-center justify-center text-slate-500 italic">
                  No printable strings extracted.
                </div>
              )}
            </div>
          </div>

          {/* Data Section Dump (objdump-lite) */}
          {result.data_section && (
            <div className="md:col-span-2 lg:col-span-3 bg-[#111928] border border-[#1f2937] border-t-2 border-t-[#00d4ff] shadow-xl shadow-black/40 p-6 rounded-sm flex flex-col h-[600px]">
              <div className="flex items-center justify-between mb-4 pb-4 border-b border-slate-700/80">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-indigo-500/20 rounded-lg">
                    <Code className="text-indigo-400" size={20} />
                  </div>
                  <h3 className="text-xl font-bold text-white">.data Section (objdump -s -j .data)</h3>
                </div>
              </div>
              
              <div className="flex-1 overflow-y-auto pr-2 rounded-lg border border-slate-800 bg-slate-900/30">
                <pre className="p-3 font-mono text-base text-slate-300 break-all whitespace-pre-wrap">{result.data_section}</pre>
              </div>
            </div>
          )}

        </div>
      )}
    </div>
  );
}
